### PR TITLE
update nexus theme for ST3

### PR DESCRIPTION
**Pull request by Raynos**
this theming fix by @LOQUILLO adds ST3 support for this theme.

### CODE REVIEW

**Comment by LOQUILLO** [comment]
Someday @EleazarCrusader will add this patch fix

**Comment by MarkHMorrison** [comment]
Thanks for adding the functionallity.

**Comment by Raynos** [comment]
@EleazarCrusader can you publish this on sublime package manager ?

**Comment by MarkHMorrison** [comment]
I believe it does automatically.

**Comment by Raynos** [comment]
@EleazarCrusader we need to update

https://github.com/wbond/package_control_channel/blob/c806bca0dfa3d66070ada3487f3f66bbdb0b7710/repository/t.json#L463

its currently configured for ST2 only.

**Comment by Raynos** [comment]
@EleazarCrusader I made a PR on package control for you ( https://github.com/wbond/package_control_channel/pull/3176 )

**Pull request merged**
